In [1]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [2]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable
credit_df = pd.read_csv("german_credit.csv")  
credit_df.head(10)

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,...,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,...,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,...,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,...,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,...,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes
5,0,no checking account,36,existing credits paid back duly till now,(vacation - does not exist?),9055,unknown/ no savings account,1 <= ... < 4 years,2,male : single,...,4,unknown / no property,35,none,for free,1,unskilled - resident,2,"yes, registered under the customers name",yes
6,0,no checking account,24,existing credits paid back duly till now,radio/television,2835,500 <= ... < 1000 DM,.. >= 7 years,3,male : single,...,4,if not A121 : building society savings agreeme...,53,none,own,1,skilled employee / official,1,none,yes
7,0,0 <= ... < 200 DM,36,existing credits paid back duly till now,car (used),6948,... < 100 DM,1 <= ... < 4 years,2,male : single,...,2,"if not A121/A122 : car or other, not in attrib...",35,none,rent,1,management/ self-employed/ highly qualified em...,1,"yes, registered under the customers name",yes
8,0,no checking account,12,existing credits paid back duly till now,domestic appliances,3059,.. >= 1000 DM,4 <= ... < 7 years,2,male : divorced/separated,...,4,real estate,61,none,own,1,unskilled - resident,1,none,yes
9,1,0 <= ... < 200 DM,30,critical account/ other credits existing (not ...,car (new),5234,... < 100 DM,unemployed,4,male : married/widowed,...,2,"if not A121/A122 : car or other, not in attrib...",28,none,own,2,management/ self-employed/ highly qualified em...,1,none,yes

In [3]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000 non-null object
people_under_maintenance      1000 non-null int64
telephone                     1000 non-null object
foreign_worker                1000 non-null object
dtypes: int64(8), object(13)
memory usage: 164.1+ KB

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [4]:
# Lets build a Ensemble model but need to modify the dataset first
data_type_change = [ 'account_check_status', 'credit_history','purpose', 'savings', 'present_emp_since', 'personal_status_sex', 'other_debtors',
'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker']
for column in data_type_change:
    if credit_df[column].dtype ==  'object':
        credit_df[column] = pd.Categorical(credit_df[column]).codes
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null int8
duration_in_month             1000 non-null int64
credit_history                1000 non-null int8
purpose                       1000 non-null int8
credit_amount                 1000 non-null int64
savings                       1000 non-null int8
present_emp_since             1000 non-null int8
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null int8
other_debtors                 1000 non-null int8
present_res_since             1000 non-null int64
property                      1000 non-null int8
age                           1000 non-null int64
other_installment_plans       1000 non-null int8
housing                       1000 non-null int8
credits_this_bank             1000 non-null int64
job                           1000 non-null int8
people_under_maintenance      1000 non-null int64
telephone                     1000 non-null int8
foreign_worker                1000 non-null int8
dtypes: int64(8), int8(13)
memory usage: 75.3 KB

In [5]:
from sklearn.model_selection import train_test_split
X = credit_df.drop("default", axis=1)
y = credit_df["default"]

In [6]:
test_size = 0.50 # taking 50:50 training and test set 
seed = 5  # Random numbmer seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [7]:
credit_df.isnull().values.any()
pd.get_dummies(credit_df)
credit_df = credit_df.replace('?', np.nan)
credit_df = credit_df.apply(lambda x: x.fillna(x.median()),axis=0)

In [47]:
# Print Shape of model data
x = pd.get_dummies(X_train)
x.shape

(300, 20)

### Check for highly correlated variables but don't required any treatment for this use case

In [9]:
credit_df.corr()

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
default,1.000000,-0.302406,0.214927,0.097054,-0.058483,0.154739,-0.129332,0.001805,0.072404,-0.089535,...,0.002967,0.034011,-0.091127,-0.053862,0.019315,-0.045732,-0.032756,-0.003015,-0.036466,0.082079
account_check_status,-0.302406,1.000000,-0.096005,-0.110683,-0.007687,-0.092638,0.134248,-0.052057,0.029780,0.049073,...,0.008835,-0.032983,0.083636,0.052184,-0.012511,0.084513,-0.029085,0.030417,0.037208,-0.014658
duration_in_month,0.214927,-0.096005,1.000000,0.029430,-0.093921,0.624984,0.072265,0.028078,0.074749,0.099678,...,0.034067,0.068363,-0.036136,0.003559,-0.157049,-0.011284,-0.215438,-0.023834,0.164718,0.138196
credit_history,0.097054,-0.110683,0.029430,1.000000,0.057882,0.029050,0.001626,0.018060,-0.059779,-0.080282,...,-0.086987,-0.051107,-0.157261,0.040499,0.084026,-0.387820,-0.013921,-0.070008,-0.039237,0.000513
purpose,-0.058483,-0.007687,-0.093921,0.057882,1.000000,-0.088610,-0.041116,0.016664,0.003199,-0.097655,...,-0.017550,-0.125088,-0.128689,0.038427,0.099185,-0.089907,-0.001895,-0.113761,-0.074844,0.029228
credit_amount,0.154739,-0.092638,0.624984,0.029050,-0.088610,1.000000,0.087976,0.074224,-0.271316,0.114810,...,0.028926,0.081618,0.032716,-0.020224,-0.135632,0.020795,-0.261139,0.017142,0.276995,0.050050
savings,-0.129332,0.134248,0.072265,0.001626,-0.041116,0.087976,1.000000,-0.043382,-0.001663,0.078204,...,0.093577,-0.035966,0.061369,-0.018960,-0.021146,-0.047965,-0.032630,0.028827,0.079551,0.012946
present_emp_since,0.001805,-0.052057,0.028078,0.018060,0.016664,0.074224,-0.043382,1.000000,-0.105237,-0.053517,...,-0.161882,-0.054509,-0.177257,0.066824,0.048259,-0.042033,-0.017382,-0.052796,0.007619,-0.009027
installment_as_income_perc,0.072404,0.029780,0.074749,-0.059779,0.003199,-0.271316,-0.001663,-0.105237,1.000000,0.118367,...,0.049302,0.025613,0.058266,0.041423,-0.089405,0.021669,-0.078090,-0.071207,0.014413,0.090024
personal_status_sex,-0.089535,0.049073,0.099678,-0.080282,-0.097655,0.114810,0.078204,-0.053517,0.118367,1.000000,...,0.020201,0.082633,0.177153,0.006637,-0.245949,0.112438,-0.040375,0.253574,0.078919,-0.049099
other_debtors,-0.028441,0.084286,-0.006711,0.011296,-0.084020,-0.037921,0.059876,-0.035166,0.014835,-0.022214,...,0.012690,-0.053943,0.028294,0.051581,-0.061302,0.017662,-0.014927,0.010990,0.050996,0.107639
present_res_since,0.002967,0.008835,0.034067,-0.086987,-0.017550,0.028926,0.093577,-0.161882,0.049302,0.020201,...,1.000000,0.107311,0.266419,-0.039284,-0.011941,0.089625,0.000450,0.042643,0.095359,0.054097
property,0.034011,-0.032983,0.068363,-0.051107,-0.125088,0.081618,-0.035966,-0.054509,0.025613,0.082633,...,0.107311,1.000000,0.166124,-0.059430,-0.352631,-0.001222,-0.008546,0.067663,0.037398,0.006595
age,-0.091127,0.083636,-0.036136,-0.157261,-0.128689,0.032716,0.061369,-0.177257,0.058266,0.177153,...,0.266419,0.166124,1.000000,-0.043787,-0.301419,0.149254,-0.001637,0.118201,0.145259,0.006151
other_installment_plans,-0.053862,0.052184,0.003559,0.040499,0.038427,-0.020224,-0.018960,0.066824,0.041423,0.006637,...,-0.039284,-0.059430,-0.043787,1.000000,0.024726,-0.022839,-0.009513,-0.057316,0.005649,0.020067
housing,0.019315,-0.012511,-0.157049,0.084026,0.099185,-0.135632,-0.021146,0.048259,-0.089405,-0.245949,...,-0.011941,-0.352631,-0.301419,0.024726,1.000000,-0.048591,0.106596,-0.114508,-0.102410,-0.063582
credits_this_bank,-0.045732,0.084513,-0.011284,-0.387820,-0.089907,0.020795,-0.047965,-0.042033,0.021669,0.112438,...,0.089625,-0.001222,0.149254,-0.022839,-0.048591,1.000000,0.004544,0.109667,0.065553,0.009717
job,-0.032756,-0.029085,-0.215438,-0.013921,-0.001895,-0.261139,-0.032630,-0.017382,-0.078090,-0.040375,...,0.000450,-0.008546,-0.001637,-0.009513,0.106596,0.004544,1.000000,0.127146,-0.365565,-0.100028
people_under_maintenance,-0.003015,0.030417,-0.023834,-0.070008,-0.113761,0.017142,0.028827,-0.052796,-0.071207,0.253574,...,0.042643,0.067663,0.118201,-0.057316,-0.114508,0.109667,0.127146,1.000000,-0.014753,-0.077071
telephone,-0.036466,0.037208,0.164718,-0.039237,-0.074844,0.276995,0.079551,0.007619,0.014413,0.078919,...,0.095359,0.037398,0.145259,0.005649,-0.102410,0.065553,-0.365565,-0.014753,1.000000,0.107401
foreign_worker,0.082079,-0.014658,0.138196,0.000513,0.029228,0.050050,0.012946,-0.009027,0.090024,-0.049099,...,0.054097,0.006595,0.006151,0.020067,-0.063582,0.009717,-0.100028,-0.077071,0.107401,1.000000

In [10]:
# Duration_in_month Vs Credit_amt is highly correlated
# Credit_amt Vs Foegin_workers is almost 50% correlated

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [11]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, recall_score, precision_score

In [12]:
test_size = 0.70 # taking 70:30 training and test set 
seed = 5  # Random numbmer seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [16]:
from sklearn.ensemble import RandomForestClassifier
rfcl = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)
rfcl = rfcl.fit(X_train, y_train)

In [17]:
rfcl.score(X_test , y_test)

0.7514285714285714

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [18]:
y_predict = rfcl.predict(X_test)
print(metrics.confusion_matrix(y_test, y_predict))

[[445  56]
 [118  81]]

In [22]:
# formula accuracy_score = TP+TN/TP+FP+FN+TN
# accuracy_score = (445+81)/(445+118+56+81) = 526/700 = 0.7514
accracy_score = rfcl.score(X_test , y_test)
accracy_score

0.7514285714285714

### Q6 Show the list of the features importance( 1 Marks)

In [48]:
# Feature importance means finding features using a Random forest classifier
# Two great features RF provides 'mean decrease impurity' and 'mean decrease accuracy'
#It shows how much each feature decreases the weighted impurity in a tree of Random Forest
# The optimal condition as impurity by using Gini method
feat_imp = pd.DataFrame()
feat_imp['feature'] = X_train.columns
feat_imp['importance'] = rfcl.feature_importances_
feat_imp

                       feature  importance
0         account_check_status    0.110891
1            duration_in_month    0.095409
2               credit_history    0.049607
3                      purpose    0.063844
4                credit_amount    0.127650
5                      savings    0.047671
6            present_emp_since    0.056731
7   installment_as_income_perc    0.043307
8          personal_status_sex    0.036603
9                other_debtors    0.014746
10           present_res_since    0.042705
11                    property    0.049023
12                         age    0.100492
13     other_installment_plans    0.032008
14                     housing    0.032242
15           credits_this_bank    0.028474
16                         job    0.034355
17    people_under_maintenance    0.011298
18                   telephone    0.019783
19              foreign_worker    0.003162

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [41]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [49]:
# Use below values
num_folds = 10
seed = 77

In [51]:
model = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)

In [52]:
#Validate the Random Forest model build above using k fold

In [54]:
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=seed)

In [55]:
result = cross_val_score(model, X, y, cv=kfold)

In [0]:
#Calculate Mean score

In [56]:
result.mean()

0.759

In [0]:
# Calculate score standard deviation using std()

In [57]:
result.std()

0.04392038251199552

# Q8 Print the confusion matrix( 1 Marks)

In [63]:
model1 = model.fit(X_train, y_train)
y_predict = model1.predict(X_test)
print(metrics.confusion_matrix(y_test, y_predict))

[[446  46]
 [134  74]]

In [79]:
from sklearn.model_selection import cross_validate
from  sklearn.metrics import accuracy_score, roc_auc_score, average_precision_score, precision_score, recall_score
# Considering default variable has 2 classes
# 0 means not default , considering this as positive case
# 1 means default , Considering this as negative case
from sklearn.metrics import roc_curve, auc
def tn(y_true, y_pred): return confusion_matrix(y_true, y_pred)[1, 1]
def fp(y_true, y_pred): return confusion_matrix(y_true, y_pred)[1, 0]
def fn(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 1]
def tp(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 0]
def accuracy(y_true, y_pred): return accuracy_score(y_true, y_pred)
def avgprecision_score(y_true, y_pred): return average_precision_score(y_true, y_pred)
def prec_score(y_true, y_pred): return precision_score(y_true, y_pred)
def recallscore(y_true, y_pred): return recall_score(y_true, y_pred)
def rocaucscore(y_true, y_pred): return roc_auc_score(y_true, y_pred)
def fpr(y_true, y_pred):
    fpr, tpr, thresholds = roc_curve(y_test, y_pred)
    return fpr

In [80]:
X.shape

(1000, 20)

In [83]:
y_train.shape

(300,)

In [84]:
from sklearn.metrics import make_scorer
scorings = {'tp': make_scorer(tp), 'tn': make_scorer(tn), 'fp': make_scorer(fp), 'fn': make_scorer(fn), 
           'accuracy' : make_scorer(accuracy), 'avgprecision_score' : make_scorer(avgprecision_score),
           'prec_score' : make_scorer(prec_score), 'recallscore':make_scorer(recallscore), 'rocaucscore':make_scorer(rocaucscore)
           }

In [85]:
from sklearn.metrics import make_scorer
scorings = {'tp': make_scorer(tp), 'tn': make_scorer(tn), 'fp': make_scorer(fp), 'fn': make_scorer(fn), 
           'accuracy' : make_scorer(accuracy), 'avgprecision_score' : make_scorer(avgprecision_score),
           'prec_score' : make_scorer(prec_score), 'recallscore':make_scorer(recallscore), 'rocaucscore':make_scorer(rocaucscore)
           }

In [88]:
cv_results = cross_validate(model1.fit(X, y), X, y, scoring=scorings, cv=kfold)

NameError: name 'confusion_matrix' is not defined

In [ ]:
cv_results

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [87]:
print(cv_results['test_recallscore']*100)

NameError: name 'cv_results' is not defined

In [0]:
print(cv_results['test_prec_score']*100)

# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [0]:
#Hint: Use roc_curve

In [94]:
from scipy import interp

In [95]:
X = x.copy()
y1 = y_train.copy()
X.reset_index(inplace=True)
X.reset_index

<bound method DataFrame.reset_index of      index  account_check_status  duration_in_month  credit_history  purpose  \
0      749                     3                 15               3        3
1      960                     3                  6               1        4
2      427                     3                 18               1        4
3      745                     1                 13               1        1
4      759                     1                 12               1        2
5      438                     1                 42               1        5
6      536                     1                  6               3        2
7      910                     3                 36               2        4
8       79                     0                 30               3        7
9      406                     3                 24               1        3
10     261                     1                 24               3        4
11     150                     3                  6               3        4
12     583                     0                 36               3        5
13     250                     1                  6               1        2
14     423                     3                 21               2        7
15     262                     1                 18               1        2
16     369                     0                 18               3        7
17     611                     2                 10               3        2
18     432                     1                  6               1        7
19     115                     3                 48               1        4
20     866                     1                 18               3        4
21     892                     1                 12               1        2
22     225                     3                 36               4        5
23     815                     0                 36               2        2
24      11                     1                 48               3        1
25     889                     3                 28               0        3
26     409                     2                 12               1        2
27     561                     1                 24               0        4
28     728                     0                 48               0        1
29     242                     1                 48               4        3
..     ...                   ...                ...             ...      ...
270    779                     0                 18               3        5
271    257                     1                 12               0        4
272    699                     2                 15               3        0
273    803                     3                 12               1        4
274    711                     1                  6               0        0
275     10                     0                 12               3        2
276    399                     3                 24               1        4
277    206                     3                 12               1        7
278    431                     0                 24               3        6
279    373                     3                 60               1        2
280    420                     3                 15               3        2
281    566                     1                 12               3        2
282    740                     1                 24               0        2
283    374                     0                 60               0        6
284    827                     3                 18               4        1
285    928                     3                 30               3        4
286    787                     3                 48               1        3
287    172                     0                 24               2        7
288    117                     1                 10               1        7
289    167                     0                 11               3        7
290    441                     1                 12               3        7
291    736                     0                 24               3        3
292    927                     1                 48               3        3
293    664                     2                  6               1        0
294    293                     2                 42               1        3
295    235                     1                 24               3        4
296    980                     0                 30               1        7
297    596                     1                 24               3        2
298    607                     0                 36               3        4
299    727                     1                 18               3        4

     credit_amount  savings  present_emp_since  installment_as_income_perc  \
0             3029        1                  3                           2
1             1740        1                  0                           2
2             1149        0                  2                           4
3             1797        1                  1                           3
4              691        1                  0                           4
5             3394        1                  4                           4
6             1374        4                  4                           4
7             4454        1                  2                           4
8             3832        1                  1                           2
9             2197        4                  3                           4
10            1603        1                  0                           4
11            1346        2                  0                           2
12            2384        1                  1                           4
13             666        0                  3                           3
14            1591        2                  3                           4
15            5302        1                  0                           2
16            3001        1                  3                           2
17            1240        2                  0                           1
18            1872        1                  4                           4
19            3578        4                  0                           4
20            2389        1                  1                           4
21            2171        1                  2                           4
22            2613        1                  2                           4
23            7432        1                  2                           2
24            4308        1                  1                           3
25            7824        4                  1                           3
26             939        3                  3                           4
27            1546        1                  3                           4
28            6416        1                  0                           4
29            4605        1                  0                           3
..             ...      ...                ...                         ...
270           3872        1                  4                           2
271           2149        1                  2                           4
272           1905        1                  0                           4
273            976        4                  0                           4
274           1198        1                  0                           4
275           1295        1                  1                           3
276           1516        0                  2                           4
277           1935        1                  0                           4
278          11328        1                  2                           2
279          13756        4                  0                           2
280           3186        0                  3                           2
281           1372        1                  3                           2
282           2325        2                  3                           2
283          14782        2                  0                           3
284           4165        1                  2                           2
285           1867        4                  0                           4
286           2751        4                  0                           4
287           2064        1                  4                           3
288           2132        4                  1                           2
289           1577        0                  1                           4
290           1620        1                  2                           2
291          11560        1                  2                           1
292          10297        1                  3                           4
293           1047        1                  2                           2
294           4796        1                  0                           4
295           1823        1                  4                           4
296           8386        1                  3                           2
297           1442        1                  3                           4
298           2671        2                  2                           4
299           1882        1                  2                           4

     personal_status_sex       ...        present_res_since  property  age  \
0                      3       ...                        2         1   33
1                      2       ...                        2         2   30
2                      3       ...                        3         2   46
3                      3       ...                        1         0   28
4                      3       ...                        3         0   35
5                      3       ...                        4         1   65
6                      0       ...                        3         0   75
7                      0       ...                        4         2   34
8                      2       ...                        1         0   22
9                      3       ...                        4         1   43
10                     0       ...                        4         1   55
11                     3       ...                        4         3   42
12                     3       ...                        1         3   33
13                     0       ...                        4         2   39
14                     3       ...                        3         2   34
15                     3       ...                        4         3   36
16                     0       ...                        4         2   40
17                     0       ...                        4         3   48
18                     3       ...                        4         3   36
19                     3       ...                        1         2   47
20                     0       ...                        1         1   27
21                     3       ...                        4         0   38
22                     3       ...                        2         1   27
23                     0       ...                        2         0   54
24                     0       ...                        4         0   24
25                     3       ...                        4         2   40
26                     2       ...                        2         2   28
27                     3       ...                        4         1   24
28                     0       ...                        3         3   59
29                     3       ...                        4         3   24
..                   ...       ...                      ...       ...  ...
270                    0       ...                        4         1   67
271                    1       ...                        1         3   29
272                    3       ...                        4         1   40
273                    3       ...                        4         1   35
274                    0       ...                        4         3   35
275                    0       ...                        1         1   25
276                    0       ...                        1         2   43
277                    3       ...                        4         2   43
278                    3       ...                        3         1   29
279                    3       ...                        4         3   63
280                    0       ...                        3         1   20
281                    1       ...                        3         1   36
282                    3       ...                        3         1   32
283                    0       ...                        4         3   60
284                    3       ...                        2         1   36
285                    3       ...                        4         1   58
286                    3       ...                        3         1   38
287                    0       ...                        2         0   34
288                    0       ...                        3         2   27
289                    0       ...                        1         2   20
290                    0       ...                        3         0   30
291                    0       ...                        4         1   23
292                    3       ...                        4         3   39
293                    0       ...                        4         0   50
294                    3       ...                        4         3   56
295                    3       ...                        2         1   30
296                    3       ...                        2         0   49
297                    0       ...                        4         1   23
298                    0       ...                        4         3   50
299                    0       ...                        4         1   25

     other_installment_plans  housing  credits_this_bank  job  \
0                          1        1                  1    1
1                          1        2                  2    1
2                          1        1                  2    1
3                          0        1                  2    3
4                          1        1                  2    1
5                          1        1                  2    2
6                          1        1                  1    0
7                          1        1                  2    1
8                          1        1                  1    1
9                          1        1                  2    1
10                         1        1                  1    1
11                         0        0                  1    1
12                         1        2                  1    3
13                         1        1                  2    3
14                         1        1                  2    0
15                         1        0                  3    0
16                         1        2                  1    1
17                         1        0                  1    3
18                         1        0                  3    0
19                         1        1                  1    1
20                         2        1                  1    1
21                         0        1                  2    3
22                         1        1                  2    1
23                         1        2                  1    1
24                         1        2                  1    1
25                         0        2                  2    1
26                         1        1                  3    1
27                         0        2                  1    3
28                         1        2                  1    1
29                         1        0                  2    1
..                       ...      ...                ...  ...
270                        1        1                  1    1
271                        1        0                  1    1
272                        1        2                  1    0
273                        1        1                  2    1
274                        1        0                  1    1
275                        1        2                  1    1
276                        1        1                  2    3
277                        1        1                  3    1
278                        0        1                  2    0
279                        0        0                  1    0
280                        1        2                  1    1
281                        1        1                  1    1
282                        0        1                  1    1
283                        0        0                  2    0
284                        2        1                  2    1
285                        1        1                  1    1
286                        1        1                  2    1
287                        1        1                  1    0
288                        1        2                  2    1
289                        1        1                  1    1
290                        1        1                  1    1
291                        1        2                  2    0
292                        2        0                  3    1
293                        1        1                  1    3
294                        1        0                  1    1
295                        2        1                  1    0
296                        1        1                  1    1
297                        1        2                  2    1
298                        1        0                  1    1
299                        0        2                  2    1

     people_under_maintenance  telephone  foreign_worker
0                           1          0               1
1                           1          0               1
2                           1          0               1
3                           1          0               1
4                           1          0               1
5                           1          0               1
6                           1          1               1
7                           1          0               1
8                           1          0               1
9                           2          1               1
10                          1          0               1
11                          2          1               1
12                          1          0               1
13                          1          1               1
14                          1          0               1
15                          1          1               1
16                          1          0               1
17                          2          0               1
18                          1          1               1
19                          1          1               1
20                          1          0               1
21                          1          0               0
22                          1          0               1
23                          1          0               1
24                          1          0               1
25                          2          1               1
26                          1          1               1
27                          1          0               1
28                          1          0               1
29                          2          0               1
..                        ...        ...             ...
270                         1          1               1
271                         1          0               1
272                         1          1               1

In [96]:
y1.reset_index(inplace=True)
X.drop(columns=['index'], inplace=True)
y1.drop(columns=['index'], inplace=True)

TypeError: Cannot reset_index inplace on a Series to create a DataFrame

In [90]:
tprs = []
aucs = []
mean_fpr = np.linspace(0, 1, 100)

i = 0
for train, test in kfold.split(X, y1):
    probas_ = model.fit(X.loc[train], y1.loc[train]).predict_proba(X.loc[test])
    # Compute ROC curve and area the curve
    fpr, tpr, thresholds = roc_curve(y1.loc[test], probas_[:, 1])
    tprs.append(interp(mean_fpr, fpr, tpr))
    tprs[-1][0] = 0.0
    roc_auc = auc(fpr, tpr)
    aucs.append(roc_auc)
    plt.plot(fpr, tpr, lw=1, alpha=0.3,
             label='ROC fold %d (AUC = %0.2f)' % (i, roc_auc))

    i += 1
plt.plot([0, 1], [0, 1], linestyle='--', lw=2, color='r',
         label='Chance', alpha=.8)

mean_tpr = np.mean(tprs, axis=0)
mean_tpr[-1] = 1.0
mean_auc = auc(mean_fpr, mean_tpr)
std_auc = np.std(aucs)
plt.plot(mean_fpr, mean_tpr, color='b',
         label=r'Mean ROC (AUC = %0.2f $\pm$ %0.2f)' % (mean_auc, std_auc),
         lw=2, alpha=.8)

std_tpr = np.std(tprs, axis=0)
tprs_upper = np.minimum(mean_tpr + std_tpr, 1)
tprs_lower = np.maximum(mean_tpr - std_tpr, 0)
plt.fill_between(mean_fpr, tprs_lower, tprs_upper, color='grey', alpha=.2,
                 label=r'$\pm$ 1 std. dev.')

plt.xlim([-0.05, 1.05])
plt.ylim([-0.05, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")
plt.show()

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [61]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [62]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(X_train, y_train)
    rfm.fit(X_, y_)
    y_pred = rfm.predict(X_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

NameError: name 'rfm' is not defined

In [0]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  0.6893333333333334
Standard deviation:  0.014966629547095768